### ISSUE TITLE
bug No damage applied

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#1121]
In GitLab by @gvoid.rift on Jan 12, 2023, 10:02

I've done a clean install of foundry (10.291), stripped it down to just 
midi 10.0.24
socketLIB 1.0.12
libwrapper 1.12.11.0
DND5e 2.1.1

and now none of my tokens will apply automated dmage 
I get an error in the log:

Uncaught (in promise) TypeError: trait.includes is not a function
[Detected 1 package: midi-qol]
    at getTraitMult (utils.js:319:34)
    at applyTokenDamageMany (utils.js:607:21)
    at async processDamageRoll (utils.js:762:20)
    at async Workflow._next (workflow.js:665:6)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)

![image](https://my-gitlab-bucket.s3.amazonaws.com/640711674/5a0c30c25466c1018e003f76acb84cb8faa29385f05ad56b25796d41b28c969b/image.png)

**Comment by tposney** [comment]
In GitLab by @Gambet on Jan 12, 2023, 18:08

This is a result of the update to the DnD5e system they just put out. A lot of modules that used the system broke as a result of that update, and they'll all have to be updated to remain compatible.

**Comment by tposney** [comment]
In GitLab by @Remedysz on Jan 12, 2023, 18:10

Yup. I dialed back my version to the old DnD5e system and it's working as normal.

**Comment by tposney** [comment]
In GitLab by @gvoid.rift on Jan 12, 2023, 21:48

which version did you roll back to?
I tried 2.1.0 but had the same issue

**Comment by tposney** [comment]
In GitLab by @thatlonelybugbear on Jan 12, 2023, 22:01

You will need dnd5e system v2.0.3

**Comment by tposney** [comment]
In GitLab by @willisterman on Jan 13, 2023, 03:06

I did a quick fix for this by adding .toObject() in src/module/util.js, line 300.  Dunno if that's the recommended approach for the new DnD5e system though.

**Comment by tposney** [comment]
In GitLab by @ivojnt on Jan 13, 2023, 04:58

This seems to be the problem from a issue I opened yesterday.
https://gitlab.com/tposney/midi-qol/-/issues/1119

**Comment by tposney** [comment]
In GitLab by @gvoid.rift on Jan 13, 2023, 05:16

thanks - this alliviates it for now

`let trait = duplicate(actor.system.traits[type].value.toObject());`

also line 305 

`const bypasses = actor.system.traits[type].bypasses.toObject() ?? [];`

**Comment by tposney** [comment]
Yes it is and should be fixed in 10.0.25/10.0.26
