### ISSUE TITLE
midi sound error when loading scene (with dnd 2.0.3)

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#1134]
In GitLab by @mmacgibbon on Jan 22, 2023, 10:31

When using 5e 2.0.3 and Midi 10.0.26, 

I get an error (I have used find a culprit to ensure its not a competing module)

midi-sounds.js:121 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getBaseItem')
[Detected 1 package: midi-qol]
    at MidiSounds.getItemBaseTypes (midi-sounds.js:121:60)
    at getWeaponBaseTypes (midi-sounds.js:106:40)

**Comment by tposney** [comment]
Thanks for that. I did not put a backward compatible version of the 2.1.2 changes. Will put the change back in 10.0.27
