### ISSUE TITLE
Can't wrap 'KeyboardManager.prototype._onFocusIn'

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#1155]
In GitLab by @gobeavs on Feb 9, 2023, 13:13

I get this error message in the console:
Uncaught (in promise) LibWrapperPackageError: lib-wrapper. Error detected in module Midi QOL. It is likely this module has not been updated for FVTT Version 10.

This is *not* a libWrapper bug.

Find information about this module here: https://gitlab.com/tposney/midi-qol
Report this issue here: https://gitlab.com/tposney/midi-qol/-/issues

== Technical Details:
Detected by libWrapper.
Package ID= midi-qol
Error= Can't wrap 'KeyboardManager.prototype._onFocusIn', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, midi-qol]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at pe (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at initPatching (patching.js:680:13)
    at Object.fn (midi-qol.js:105:2)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.initialize (foundry.js:7767:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)

I'm using Foundry V10.290 and Midi-QOL version10.0.29

**Comment by tposney** [comment]
Can you update to foundry 10.291. There's a fix introduced in midi 10.0.27 for keyboard handling that requires (I think) 10.291 of foundry

**Comment by tposney** [comment]
In GitLab by @gobeavs on Feb 20, 2023, 04:57

This cleared up the problem.  
Thank you
