### ISSUE TITLE
[10.0.37] - Damage Formula that results in 0 damage triggers TypeError: undefined reading 'terms' in utils.js:32

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#1234]
In GitLab by @thatlonelybugbear on Apr 27, 2023, 22:58

A damage formula that sums up to `0` eg Unarmed Strike with a -1 strength mod or straight up 0.
```js
utils.js:32 
 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'terms')
[Detected 1 package: midi-qol]
    at createDamageList (utils.js:32:25)
    at Workflow._next (workflow.js:570:25)
    at async Workflow.next (workflow.js:255:10)
```

I tried to follow the error stack trying to see how to implement a non-zero check for the damageList that is created, but was a bit lost.

**Comment by tposney** [comment]
In GitLab by @thatlonelybugbear on Apr 28, 2023, 24:43

10.0.38 fixes so I will close this.
