### ISSUE TITLE
'Skip consume resource dialog' breaks spells

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#680]
In GitLab by @semikel on Feb 5, 2022, 05:41

I randomly noticed that with 'Skip consume resource dialog' checked I now get an error:

`
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fastForward')
[Detected 3 packages: midi-qol, lib-wrapper, system:dnd5e]
    at Item5e.doItemRoll (itemhandling.js:493:53)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at Item5e.🎁CONFIG.Item.documentClass.prototype.roll#0 (libWrapper-wrapper.js:189:20)
    at ActorSheet5eCharacter._onItemRoll (base.js:908:29)
    at HTMLDivElement.<anonymous> (base.js:618:62)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at HTMLDivElement.v.handle (jquery.min.js:2:41048)
`

I was in the middle of trying to figure out why effects like Bless aren't applying to targets, so I'm not sure what I did that may have broken it, but I disabled every other module, aside from DAE, libWrapper and socketlib.

Here are my settings [fvtt-midi-qol-settings.json](https://my-gitlab-bucket.s3.amazonaws.com/640711674/845b48e143c657a20d4e45a96e54e3946250204f4ba5a71525c160b96e1e58a1/fvtt-midi-qol-settings.json)

**Comment by tposney** [comment]
Fix went out in 0.9.08
