### ISSUE TITLE
Exceptions logged to console when canvas is disabled.

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#695]
In GitLab by @watermelonwolverine on Feb 15, 2022, 05:11

When the "Disabled Game Canvas" option is checked in the settings there are exceptions logged into the browser's console. Sometimes they appear by themselves, but they always appear when rolling dice.  

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isEnabled')  
[Detected 1 package: midi-qol]  
    at dice3dEnabled (modules/midi-qol/src/module/setupModules.js:46:94)  
    at diceSoNiceHandler (modules/midi-qol/src/module/chatMesssageHandling.js:251:7)  
    at modules/midi-qol/src/module/Hooks.js:147:3  
    at Function._call (foundry.js:294:14)  
    at Function.call (foundry.js:279:33)  
    at ChatMessage.getHTML (foundry.js:15218:11)  
    at async ChatLog._renderBatch (foundry.js:57535:21)  
    at async ChatLog._renderInner (foundry.js:57505:5)  
    at async ChatLog._render (foundry.js:3068:19)  
    at async ChatLog._render (foundry.js:46890:5)  
    at async ChatLog._render (foundry.js:57496:5)

**Comment by tposney** [comment]
I'm surprised it works at all with the canvas disabled - but thanks for the heads up. I'll put a fix in 0.9.14
