### ISSUE TITLE
Error - Token Action - Can't use weapon or feature - Potentially a result of late targeting

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#798]
In GitLab by @aamileto27 on Apr 1, 2022, 23:51

Hi Community, when trying to use the Token action HUD to perform a weapon attack, I get the following error in the console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lateTargeting')
[Detected 3 packages: midi-qol, lib-wrapper, token-action-hud]
    at Item5e.doItemRoll (itemhandling.js:445:31)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at Item5e.🎁CONFIG.Item.documentClass.prototype.roll#0 (libWrapper-wrapper.js:189:20)
    at RollHandlerBase5e.rollItemMacro (bundle.min.js:1:66648)
    at RollHandlerBase5e._handleMacros (bundle.min.js:1:66045)
    at RollHandlerBase5e.doHandleActionEvent (bundle.min.js:1:65691)
    at RollHandlerBase5e.handleActionEvent (bundle.min.js:1:33222)
    at handleClick (bundle.min.js:1:10135)
    at HTMLDivElement.<anonymous> (bundle.min.js:1:10791)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at HTMLDivElement.v.handle (jquery.min.js:2:41048)
```
When I turn off late targeting, it doesn't throw this error, and the token action HUD performs as normal. 
Just thought I'd mention it here to let others know!
Thanks

**Comment by tposney** [comment]
Thanks for the heads up. Fix in 0.9.42
