### ISSUE TITLE
SW5e: Error when rolling damage

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#811]
In GitLab by @TogaParty on Apr 12, 2022, 03:42

I get the following error when rolling damage.  I'm not sure what the root cause is, but this seems to happen pretty early in the workflow.  I have automatic detection enabled for hits, but can't roll damage, and the automatic saving throws don't fire.

foundry.js:2150 Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: midi-qol]
    at ClientSettings.get (foundry.js:2150:42)
    at Item5e.doDamageRoll (itemhandling.js:296:54)
    at async Workflow._next (workflow.js:504:6)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)

**Comment by tposney** [comment]
In GitLab by @TogaParty on Apr 12, 2022, 03:43

Note that damage isn't actually rolled, and in this case I am not automatically rolling it, but prompting the user/GM to roll.

**Comment by tposney** [comment]
The settings being checked are 
```js
game.settings.get(game.system.id, "criticalDamageMaxDice");
game.settings.get(game.system.id, "criticalDamageModifiers");
```
I can confirm that on the latest release I have access to (1.5.7.2.1) there is no error on on rolling a critical. Can you make sure you have the latest version of sw5e?

**Comment by tposney** [comment]
Please reopen if making sure you have the latest sw5e does not fix the problem
