### ISSUE TITLE
Support ready set roll - the successor to better rolls.

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#997]
In GitLab by @tposney on Sep 12, 2022, 24:02

**Comment by tposney** [comment]
In GitLab by @thatlonelybugbear on Sep 12, 2022, 08:02

Hmmm maybe I should have opened a new issue, so let me know if this needs to be moved elsewhere, but I thought is due to checks for BR being present.

I am not using BR or the new RSR.

in v10.0.10, when a caster who is concentrating is damaged, the concentration card pops up, but no concentration roll is happening.
Instead an error pops up in console:
```js
 midi-qol |  Token  Token5e {#controlled: true, #hover: false, #initialize: ƒ, #animateFrame: ƒ, #getMovementSource: ƒ, …} could not roll save/check assuming 0
error @ midi-qol.js:24
checkSaves @ workflow.js:2216
``` 
followed by 
```js
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isBR')
[Detected 1 package: midi-qol]
    at Workflow.checkSaves (workflow.js:2251:16)
    at async Workflow._next (workflow.js:607:7)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)
    at async Workflow.next (workflow.js:267:10)
```
The line in question from workflow.js:2251 `if (!result.isBR && !saved) {`


[v10Bugbears-midi-qol-settings.json](https://my-gitlab-bucket.s3.amazonaws.com/640711674/2e90a1319c96eb23e674f48cc7ec7a858d494e710d857acbe3366f40d5edf89f/v10Bugbears-midi-qol-settings.json)

**Comment by tposney** [comment]
Are you using LMRTFY?

**Comment by tposney** [comment]
In GitLab by @thatlonelybugbear on Sep 12, 2022, 23:18

Tested some more as I was just following up with a comment of a user in discord.

I think the issue arises when there is an effect on the saving actor `flags.midi-qol.advantage.concentration | Custom | 1` (or Override 1)

If the effect value is blank, the concentration save goes forward (with no advantage however).

I might have missed something whether these flags actually work or not and how, as I am actually a bit lost with ping ponging between v9 and v10 at the moment :slight_smile:

**Comment by tposney** [comment]
In GitLab by @Z8MB1E on Oct 6, 2022, 09:24

Is support for RSR still being added/considered? I'd _love_ to see this working together with RSR.
